version: '3.8'

services:
  tcp-server:
    build:
      context: .
    ports:
      - 7890:7890
    volumes:
      - "./config.json:/app/config.json"
    deploy:
      restart_policy:
        condition: on-failure
